/**
 * Generate API client type declarations for scaffolded projects.
 * @since 1.0.0
 */
import { Effect } from "effect";

export interface ApiClientTypesOptions {
  readonly apiTypeImportPath: string;
}

export const generateApiClientTypes = (options: ApiClientTypesOptions): Effect.Effect<string> =>
  Effect.succeed(
    `// Auto-generated by trygg\ndeclare module "trygg/api" {\n  import type * as Context from "effect/Context"\n  import type { Layer } from "effect"\n  import type { HttpApiClient } from "effect/unstable/httpapi"\n  import type { Api } from "${options.apiTypeImportPath}"\n\n  type ApiClientService = HttpApiClient.ForApi<typeof Api>\n\n  export interface ApiClient {}\n  export const ApiClient: Context.ServiceClass<ApiClient, "ApiClient", ApiClientService>\n  export const ApiClientLive: Layer.Layer<ApiClient>\n}\n\nexport {}\n`,
  );
