/**
 * Generate API client type declarations for scaffolded projects.
 * @since 1.0.0
 */
import { Effect } from "effect";

export interface ApiClientTypesOptions {
  readonly apiTypeImportPath: string;
}

export const generateApiClientTypes = (options: ApiClientTypesOptions): Effect.Effect<string> =>
  Effect.succeed(
    `// Auto-generated by trygg\nimport type * as Context from "effect/Context"\nimport type { Layer } from "effect/Layer"\nimport type { HttpApiClient } from "effect/unstable/httpapi"\nimport type { Api } from "${options.apiTypeImportPath}"\n\ntype ApiClientService = HttpApiClient.ForApi<typeof Api>\n\ndeclare module "trygg/api" {\n  export interface ApiClient {}\n  export const ApiClient: Context.ServiceClass<ApiClient, "ApiClient", ApiClientService>\n  export const ApiClientLive: Layer.Layer<ApiClient>\n  export { Api }\n}\n`,
  );
