// @generated by type-tests/verify-jsx-requirement-fixture.ts. Do not edit directly.
import {
  jsx as __tryggJsx,
  jsxs as __tryggJsxs,
  Fragment as __tryggFragment,
} from "trygg/jsx-runtime";
import { expectError, expectType } from "tsd";
import { Context, Layer } from "effect";
import { Component, mount, type ComponentProps } from "trygg";
class ThemeStore extends Context.Service<
  ThemeStore,
  {
    readonly value: string;
  }
>()("test/ThemeStore") {}
type ComponentRequirements<C> =
  C extends Component.Type<infer _Props, infer _Error, infer Requirements> ? Requirements : never;
const ThemeButton = Component.gen(function* () {
  const theme = yield* ThemeStore;
  return __tryggJsx("button", {
    children: theme.value,
  });
});
const ThemedCard = Component.gen(function* () {
  const theme = yield* ThemeStore;
  return __tryggJsx("article", {
    children: theme.value,
  });
});
const ThemedTitle = Component.gen(function* (
  Props: ComponentProps<{
    readonly title: string;
  }>,
) {
  const { title } = yield* Props;
  const theme = yield* ThemeStore;
  return __tryggJsx("h3", {
    children: `${title}: ${theme.value}`,
  });
});
const ThemeExample = Component.gen(function* () {
  return __tryggJsxs("section", {
    children: [
      __tryggJsx(ThemeButton, null),
      __tryggJsx(ThemedCard, null),
      __tryggJsx(ThemedTitle, {
        title: "Using Component API",
      }),
    ],
  });
});
declare const themeButtonRequirements: ComponentRequirements<typeof ThemeButton>;
declare const themeExampleRequirements: ComponentRequirements<typeof ThemeExample>;
expectType<ThemeStore>(themeButtonRequirements);
expectType<ThemeStore>(themeExampleRequirements);
const root = document.createElement("div");
expectError(mount(root, __tryggJsx(ThemeExample, null)));
const ThemeStoreLive = Layer.succeed(ThemeStore, { value: "dark" });
const ProvidedThemeExample = ThemeExample.pipe(Component.provide(ThemeStoreLive));
declare const providedThemeExampleRequirements: ComponentRequirements<typeof ProvidedThemeExample>;
expectType<never>(providedThemeExampleRequirements);
mount(root, __tryggJsx(ProvidedThemeExample, null));
