// @generated by type-tests/verify-jsx-requirement-fixture.ts. Do not edit directly.
import {
  jsx as __tryggJsx,
  jsxs as __tryggJsxs,
  Fragment as __tryggFragment,
} from "trygg/jsx-runtime";
import { expectError, expectType } from "tsd";
import { Context, Effect, Layer } from "effect";
import { Component, mount, Signal, type ComponentProps } from "trygg";
import { Route } from "trygg/router";
class ThemeStore extends Context.Service<
  ThemeStore,
  {
    readonly value: string;
  }
>()("test/ThemeStore") {}
class UserRepository extends Context.Service<
  UserRepository,
  {
    readonly getUser: (id: string) => Effect.Effect<{
      readonly id: string;
      readonly name: string;
    }>;
  }
>()("test/UserRepository") {}
type ComponentRequirements<C> =
  C extends Component.Type<infer _Props, infer _Error, infer Requirements> ? Requirements : never;
const ThemeButton = Component.gen(function* () {
  const theme = yield* ThemeStore;
  return __tryggJsx("button", {
    children: theme.value,
  });
});
const ThemedCard = Component.gen(function* () {
  const theme = yield* ThemeStore;
  return __tryggJsx("article", {
    children: theme.value,
  });
});
const ThemedTitle = Component.gen(function* (
  Props: ComponentProps<{
    readonly title: string;
  }>,
) {
  const { title } = yield* Props;
  const theme = yield* ThemeStore;
  return __tryggJsx("h3", {
    children: `${title}: ${theme.value}`,
  });
});
const ThemeExample = Component.gen(function* () {
  return __tryggJsxs("section", {
    children: [
      __tryggJsx(ThemeButton, null),
      __tryggJsx(ThemedCard, null),
      __tryggJsx(ThemedTitle, {
        title: "Using Component API",
      }),
    ],
  });
});
const UserRepositoryLive = Layer.succeed(UserRepository, {
  getUser: (id) => Effect.succeed({ id, name: id === "1" ? "Ada Lovelace" : "Grace Hopper" }),
});
const UserProfile = Component.gen(function* (
  Props: ComponentProps<{
    readonly userId: Signal.Signal<string>;
  }>,
) {
  const { userId } = yield* Props;
  const repo = yield* UserRepository;
  const id = yield* Signal.get(userId);
  const user = yield* repo.getUser(id);
  return __tryggJsx("p", {
    children: user.name,
  });
});
const ProfileCard = Component.gen(function* (
  Props: ComponentProps<{
    readonly userId: Signal.Signal<string>;
  }>,
) {
  const { userId } = yield* Props;
  return __tryggJsxs("article", {
    children: [
      __tryggJsx("h2", {
        children: "User profile",
      }),
      __tryggJsx(UserProfile, {
        userId: userId,
      }),
    ],
  });
});
const App = Component.gen(function* () {
  const userId = yield* Signal.make("1");
  return __tryggJsx(ProfileCard, {
    userId: userId,
  });
});
const ProvidedApp = App.pipe(Component.provide(UserRepositoryLive));
declare const themeButtonRequirements: ComponentRequirements<typeof ThemeButton>;
declare const themeExampleRequirements: ComponentRequirements<typeof ThemeExample>;
declare const profileCardRequirements: ComponentRequirements<typeof ProfileCard>;
declare const appRequirements: ComponentRequirements<typeof App>;
declare const providedAppRequirements: ComponentRequirements<typeof ProvidedApp>;
expectType<ThemeStore>(themeButtonRequirements);
expectType<ThemeStore>(themeExampleRequirements);
expectType<UserRepository>(profileCardRequirements);
expectType<UserRepository>(appRequirements);
expectType<never>(providedAppRequirements);
const root = document.createElement("div");
expectError(mount(root, __tryggJsx(ThemeExample, null)));
const ThemeStoreLive = Layer.succeed(ThemeStore, { value: "dark" });
const ProvidedThemeExample = ThemeExample.pipe(Component.provide(ThemeStoreLive));
declare const providedThemeExampleRequirements: ComponentRequirements<typeof ProvidedThemeExample>;
expectType<never>(providedThemeExampleRequirements);
mount(root, __tryggJsx(ProvidedThemeExample, null));
expectError(Route.make("/profile").component(App));
Route.make("/profile").component(ProvidedApp);
expectError(Route.index(App));
Route.index(ProvidedApp);
const LazyApp = () => Promise.resolve({ default: App });
const LazyProvidedApp = () => Promise.resolve({ default: ProvidedApp });
expectError(Route.make("/lazy-profile").component(LazyApp));
Route.make("/lazy-profile").component(LazyProvidedApp);
