import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Config, Effect } from "effect";
import { transformTryggJsxForRequirements } from "../src/vite/jsx-requirement-transform.js";

const here = dirname(fileURLToPath(import.meta.url));
const inputPath = join(here, "..", "src", "vite", "__fixtures__", "component-requirements.raw.tsx");
const outputPath = join(here, "component-requirements-virtual-jsx.test-d.ts");

const formatFixture = Effect.fn("verifyJsxRequirementFixture.formatFixture")(function* (
  source: string,
) {
  const result = yield* Effect.sync(() =>
    spawnSync("bunx", ["oxfmt", "--stdin-filepath", outputPath], {
      input: source,
      encoding: "utf8",
    }),
  );

  if (result.status !== 0) {
    return yield* Effect.fail(
      result.stderr || "Failed to format generated JSX requirement fixture",
    );
  }

  return result.stdout;
});

const program = Effect.gen(function* () {
  const source = yield* Effect.sync(() => readFileSync(inputPath, "utf8"));
  const result = transformTryggJsxForRequirements(source, inputPath);

  if (!result.transformed) {
    return yield* Effect.fail(
      `Expected ${inputPath} to contain JSX that the Trygg requirement transform lowers.`,
    );
  }

  const expected = yield* formatFixture(
    `// @generated by type-tests/verify-jsx-requirement-fixture.ts. Do not edit directly.\n${result.code}`,
  );
  const actual = yield* Effect.try({
    try: () => readFileSync(outputPath, "utf8"),
    catch: () => "",
  }).pipe(Effect.catch(() => Effect.succeed("")));

  if (actual !== expected) {
    const shouldUpdate = yield* Config.string("UPDATE_JSX_REQUIREMENT_FIXTURE").pipe(
      Config.withDefault("0"),
    );
    if (shouldUpdate === "1") {
      yield* Effect.sync(() => writeFileSync(outputPath, expected));
      return;
    }

    return yield* Effect.fail(
      "JSX requirement tsd fixture is stale. Run UPDATE_JSX_REQUIREMENT_FIXTURE=1 bun ./type-tests/verify-jsx-requirement-fixture.ts from packages/core.",
    );
  }
});

await Effect.runPromise(
  program.pipe(
    Effect.catch((message) =>
      Effect.sync(() => {
        console.error(message);
        process.exitCode = 1;
      }),
    ),
  ),
);
