/**
 * Router types for `trygg/router`.
 *
 * @remarks
 * Owner module for the router's shared public types. This module owns the type
 * vocabulary for route params, navigation state, link typing, and the router
 * service interface.
 *
 * ## Type-Safe Routing
 *
 * This module provides type utilities for type-safe navigation:
 *
 * ```tsx
 * // Path autocomplete and param validation
 * <Link to="/users/:id" params={{ id: "123" }}>User</Link>
 *
 * // TypeScript error: missing required param
 * <Link to="/users/:id">User</Link>
 * ```
 * @since 1.0.0
 * @module trygg/router/types
 */
import { Effect, Schema, type Cause, type Scope } from "effect";
import { Component } from "../primitives/component.js";
import type { Signal } from "../primitives/signal.js";
import type { Element } from "../primitives/element.js";
import type { ScrollStrategyType } from "./scroll-strategy.js";
import type { NavigationPrefetchState, ScrollIntent } from "./navigation-outlet-coordination.js";
import type { Router } from "./service.js";
import {
  compileRoutePathPattern,
  interpolateCompiledRoutePathPattern,
  type InvalidRoutePathPattern,
  type InvalidRoutePathParamValue,
  type MissingRoutePathParam,
  type UnusedRoutePathParam,
} from "./path-pattern.js";

// ==========================================
// Errors
// ==========================================

/**
 * Error representing a failed navigation operation.
 * Wraps underlying platform errors (HistoryError, LocationError, etc.)
 * so consumers can handle navigation failures explicitly.
 *
 * @remarks
 * `NavigationError` is the typed failure surfaced by router navigation helpers
 * when platform history or location work fails.
 *
 * @example
 * ```ts
 * const error = new NavigationError({ operation: "pushState", cause: "boom" })
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export class NavigationError extends Schema.TaggedError<NavigationError>()("NavigationError", {
  operation: Schema.String,
  cause: Schema.Unknown,
}) {}

/**
 * Decoded params were requested for a pattern outside the active route chain.
 *
 * @remarks
 * `Router.params(path)` validates the requested pattern at runtime before
 * narrowing to its generated decoded type.
 *
 * @example
 * ```ts
 * const error = new RouteParamsPatternMismatch({
 *   requestedPattern: "/users/:id",
 *   activePatterns: ["/"],
 * })
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export class RouteParamsPatternMismatch extends Schema.TaggedError<RouteParamsPatternMismatch>()(
  "RouteParamsPatternMismatch",
  {
    requestedPattern: Schema.String,
    activePatterns: Schema.Array(Schema.String),
  },
) {}

/**
 * RouteComponent value was neither a Component.Type nor Effect<Element>.
 * Indicates a bug in route definition or schema validation.
 *
 * @remarks
 * `InvalidRouteComponent` signals that a route component slot received a value
 * outside the supported `RouteComponent | ComponentLoader` surface.
 *
 * @example
 * ```ts
 * const error = new InvalidRouteComponent({ actual: null })
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export class InvalidRouteComponent extends Schema.TaggedError<InvalidRouteComponent>()(
  "InvalidRouteComponent",
  {
    actual: Schema.Unknown,
  },
) {}

// ==========================================
// Route Map (augmented by vite plugin)
// ==========================================

/**
 * Route map interface - augmented by vite plugin with actual routes.
 *
 * @remarks
 * `RouteMap` is the declaration-merge target used by the Vite plugin to add
 * concrete route paths and param types to `trygg/router`.
 *
 * When using file-based routing, the vite plugin generates a routes.d.ts
 * that augments this interface with your actual route paths and params.
 *
 * @example
 * ```ts
 * // Generated by vite plugin in routes.d.ts:
 * declare module "trygg/router" {
 *   interface RouteMap {
 *     "/": {}
 *     "/users": {}
 *     "/users/:id": { readonly id: string }
 *   }
 * }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouteMap {
  // Augmented by vite plugin
}

/**
 * Generated URL-construction parameter inputs for known routes.
 *
 * @remarks
 * The Vite plugin augments this map from each params Schema's encoded type.
 * `Link` and navigation use it separately from decoded {@link RouteMap} values.
 *
 * @example
 * ```ts
 * interface Inputs extends RouteInputMap {}
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouteInputMap {
  // Augmented by vite plugin
}

/**
 * Generated Schema-decoded query values for known routes.
 *
 * @remarks
 * The Vite plugin augments this map from each query Schema's output type for
 * typed `Router.query` access.
 *
 * @example
 * ```ts
 * interface Queries extends RouteQueryMap {}
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouteQueryMap {
  // Augmented by vite plugin
}

/**
 * Generated URL-construction query inputs for known routes.
 *
 * @remarks
 * The Vite plugin augments this map from each query Schema's encoded type so
 * URL construction cannot accidentally receive decoded domain values.
 *
 * @example
 * ```ts
 * interface QueryInputs extends RouteQueryInputMap {}
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouteQueryInputMap {
  // Augmented by vite plugin
}

/**
 * Route component type - Component.gen result or Effect<Element>.
 * Can be created with Component.gen or a plain Effect that produces an Element.
 *
 * @remarks
 * `RouteComponent` is the direct component shape the router knows how to render
 * without going through a lazy loader.
 *
 * @example
 * ```ts
 * type Page = RouteComponent
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteComponent<R = unknown> =
  | Component.Type<never, unknown, R>
  | Effect.Effect<Element, unknown, R>;

type DirectRouteComponentRequirements<C> =
  C extends Component.Type<never, unknown, infer R>
    ? R
    : C extends Effect.Effect<Element, unknown, infer R>
      ? R
      : never;

type LoadedRouteComponentRequirements<Loaded> = Loaded extends {
  readonly default: infer Default;
}
  ? RouteComponentInputRequirements<Default>
  : RouteComponentInputRequirements<Loaded>;

/**
 * Extract service requirements from a direct route component or lazy loader.
 * @internal
 */
export type RouteComponentInputRequirements<C> = C extends () => Promise<infer Loaded>
  ? LoadedRouteComponentRequirements<Loaded>
  : DirectRouteComponentRequirements<C>;

type RouterProvidedRequirements = Scope.Scope | Router;

type MissingRouteComponentRequirements<C> = Exclude<
  RouteComponentInputRequirements<C>,
  RouterProvidedRequirements
>;

type IsUnknown<T> = unknown extends T ? ([T] extends [unknown] ? true : false) : false;

/**
 * Branded route-definition error shown when a route component still requires services.
 * @internal
 */
export interface UnprovidedRouteComponentRequirements<R> {
  readonly "trygg/router: route component still requires services": R;
  readonly "missing service requirements": R;
  readonly "fix: pipe the component through Component.provide(ServiceLive) before passing it to the route definition": R;
}

/**
 * Add a helpful branded error when a route component's requirements are not `never`.
 * @internal
 */
export type RouteComponentInput<C extends ComponentInput> = C &
  ([MissingRouteComponentRequirements<C>] extends [never]
    ? unknown
    : IsUnknown<MissingRouteComponentRequirements<C>> extends true
      ? unknown
      : UnprovidedRouteComponentRequirements<MissingRouteComponentRequirements<C>>);

/**
 * Lazy loader function produced by the vite transform.
 * At build time, default imports become `.component(() => import("./page"))`,
 * while named imports become `.component(() => import("./page").then((m) => m.Page))`.
 *
 * @remarks
 * `ComponentLoader` is the lazy route-component shape used after the Vite
 * transform rewrites eager component references. A loader may resolve to an ESM
 * module object with a default export or directly to a RouteComponent from a
 * named export.
 *
 * @example
 * ```ts
 * const defaultLoader: ComponentLoader = () => import("./page")
 * const namedLoader: ComponentLoader = () => import("./page").then((m) => m.Page)
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type ComponentLoader<Loaded = RouteComponent | { readonly default: unknown }> =
  () => Promise<Loaded>;

/**
 * Value stored in RouteDefinition component fields.
 * Either a direct RouteComponent (dev/eager) or a ComponentLoader (vite transform/lazy).
 *
 * @remarks
 * `ComponentInput` is the full route-component input surface accepted by route
 * builders and consumed by the outlet.
 *
 * @example
 * ```ts
 * type Input = ComponentInput
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type ComponentInput = RouteComponent | ComponentLoader;

/**
 * Get all route paths from RouteMap.
 * Uses `(string & Record<never, never>)` pattern for autocomplete with string fallback.
 *
 * @remarks
 * `RoutePath` keeps editor autocomplete for known routes while still accepting
 * arbitrary strings before a route map has been generated.
 *
 * @example
 * ```ts
 * const path: RoutePath = "/users/:id"
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RoutePath = keyof RouteMap | (string & Record<never, never>);

// ==========================================
// Type-Safe Routing Utilities
// ==========================================

type CleanParamName<P extends string> = P extends `${infer Name}*`
  ? Name
  : P extends `${infer Name}+`
    ? Name
    : P;

/**
 * Extract route params from a path pattern.
 * Uses template literal types to parse :param segments.
 *
 * @remarks
 * `ExtractRouteParams` is the path-to-param utility used as the fallback when a
 * generated `RouteMap` entry is not available.
 *
 * @example
 * ```ts
 * type P1 = ExtractRouteParams<"/users/:id">
 * // { readonly id: string }
 *
 * type P2 = ExtractRouteParams<"/posts/:postId/comments/:commentId">
 * // { readonly postId: string; readonly commentId: string }
 *
 * type P3 = ExtractRouteParams<"/about">
 * // {}
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type ExtractRouteParams<T extends string> =
  // Handle :param/rest pattern
  T extends `${infer _Start}:${infer Param}/${infer Rest}`
    ? { readonly [K in CleanParamName<Param>]: string } & ExtractRouteParams<`/${Rest}`>
    : // Handle trailing :param pattern
      T extends `${infer _Start}:${infer Param}`
      ? { readonly [K in CleanParamName<Param>]: string }
      : // No params found
        {};

type ExtractRouteParamInputs<T extends string> =
  T extends `${infer _Start}:${infer Param}/${infer Rest}`
    ? {
        readonly [K in CleanParamName<Param>]: string | number;
      } & ExtractRouteParamInputs<`/${Rest}`>
    : T extends `${infer _Start}:${infer Param}`
      ? { readonly [K in CleanParamName<Param>]: string | number }
      : {};

/**
 * Simplify intersection types for better display
 * @internal
 */
type Simplify<T> = { [K in keyof T]: T[K] } & {};

/**
 * Check if a type has any keys
 * @internal
 */
export type HasKeys<T> = keyof T extends never ? false : true;

/**
 * Get route params type for a path.
 * Uses RouteMap if available (from vite plugin), otherwise extracts from path pattern.
 *
 * @remarks
 * `RouteParamsFor` describes decoded values returned by `Router.params`.
 * URL construction uses {@link RouteParamsInputFor} instead.
 *
 * @example
 * ```ts
 * // With RouteMap (vite plugin):
 * type P1 = RouteParamsFor<"/users/:id">  // RouteMap["/users/:id"]
 *
 * // Without RouteMap (fallback):
 * type P2 = RouteParamsFor<"/posts/:postId">  // { readonly postId: string }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteParamsFor<Path extends string> = Path extends keyof RouteMap
  ? Simplify<RouteMap[Path]>
  : Simplify<ExtractRouteParams<Path>>;

/**
 * URL-safe parameter inputs for constructing a route path.
 *
 * @remarks
 * Known routes use {@link RouteInputMap}; other literal patterns fall back to
 * string-or-number inputs supported by the path interpolator.
 *
 * @example
 * ```ts
 * type UserInput = RouteParamsInputFor<"/users/:id">
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteParamsInputFor<Path extends string> = Path extends keyof RouteInputMap
  ? Simplify<RouteInputMap[Path]>
  : Simplify<ExtractRouteParamInputs<Path>>;

/**
 * Query values accepted by URL construction without a generated query Schema.
 *
 * @remarks
 * Undefined values are omitted rather than serialized as the text `undefined`.
 *
 * @example
 * ```ts
 * const query: RouteQueryInput = { page: "2", filter: undefined }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteQueryInput = Readonly<Record<string, string | undefined>>;

/**
 * Schema-decoded query values for a route path.
 *
 * @remarks
 * Known routes use {@link RouteQueryMap}; paths without generated query
 * metadata retain an unknown-value record.
 *
 * @example
 * ```ts
 * type SearchQuery = RouteQueryFor<"/search">
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteQueryFor<Path extends string> = Path extends keyof RouteQueryMap
  ? Simplify<RouteQueryMap[Path]>
  : Record<string, unknown>;

/**
 * Encoded query values accepted when constructing a route URL.
 *
 * @remarks
 * Known routes use {@link RouteQueryInputMap}; other paths accept the generic
 * string-valued {@link RouteQueryInput} transport shape.
 *
 * @example
 * ```ts
 * type SearchInput = RouteQueryInputFor<"/search">
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteQueryInputFor<Path extends string> = Path extends keyof RouteQueryInputMap
  ? Simplify<RouteQueryInputMap[Path]>
  : RouteQueryInput;

/**
 * Props for type-safe Link component.
 *
 * @remarks
 * `TypeSafeLinkProps` expresses the core conditional typing used by `LinkProps`
 * without the extra forwarded-attribute fields. Params and query use generated
 * encoded input maps rather than decoded route values.
 *
 * When the path contains dynamic segments (`:param`), the `params` prop is required.
 * When the path is static, `params` is optional/unnecessary.
 *
 * @example
 * ```tsx
 * // Static path - no params needed
 * <Link to="/">Home</Link>
 *
 * // Dynamic path - params required
 * <Link to="/users/:id" params={{ id: "123" }}>User</Link>
 *
 * // TypeScript enforces correct param names
 * <Link to="/users/:id" params={{ wrong: "x" }}>Error!</Link>
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type TypeSafeLinkProps<Path extends string> =
  HasKeys<RouteParamsInputFor<Path>> extends true
    ? {
        readonly to: Path;
        readonly params: RouteParamsInputFor<Path>;
        readonly query?: RouteQueryInputFor<Path>;
        readonly replace?: boolean;
        readonly children?: unknown;
        readonly className?: string;
      }
    : {
        readonly to: Path;
        readonly params?: never;
        readonly query?: RouteQueryInputFor<Path>;
        readonly replace?: boolean;
        readonly children?: unknown;
        readonly className?: string;
      };

/**
 * Build a URL path by substituting params into a pattern.
 *
 * @remarks
 * `buildPathWithParams` is the typed path interpolator used when a route path
 * and its params should stay aligned at compile time.
 *
 * @example
 * ```ts
 * buildPathWithParams("/users/:id", { id: "123" })
 * // "/users/123"
 *
 * buildPathWithParams("/posts/:postId/comments/:commentId", { postId: "1", commentId: "2" })
 * // "/posts/1/comments/2"
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export const buildPathWithParams: <Path extends string>(
  path: Path,
  params: RouteParamsInputFor<Path>,
) => Effect.Effect<
  string,
  | InvalidRoutePathPattern
  | MissingRoutePathParam
  | UnusedRoutePathParam
  | InvalidRoutePathParamValue
> = Effect.fn("RouterTypes.buildPathWithParams")(function* <Path extends string>(
  path: Path,
  params: RouteParamsInputFor<Path>,
) {
  const pattern = yield* compileRoutePathPattern(path);
  return yield* interpolateCompiledRoutePathPattern(pattern, params);
});

/**
 * Interpolate params into a path pattern using NavigateOptions.params.
 * Handles both string and number values (numbers are converted via String()).
 *
 * @example
 * ```ts
 * interpolateParams("/users/:id", { id: 123 })
 * // "/users/123"
 * ```
 *
 * @internal
 */
export const interpolateParams: (
  path: string,
  params: Record<string, string | number>,
) => Effect.Effect<
  string,
  | InvalidRoutePathPattern
  | MissingRoutePathParam
  | UnusedRoutePathParam
  | InvalidRoutePathParamValue
> = Effect.fn("RouterTypes.interpolateParams")(function* (
  path: string,
  params: Record<string, string | number>,
) {
  const pattern = yield* compileRoutePathPattern(path);
  return yield* interpolateCompiledRoutePathPattern(pattern, params);
});

// ==========================================
// Basic Types
// ==========================================

/**
 * Route parameters extracted from path
 *
 * @remarks
 * `RouteParams` is the raw string-valued param record stored on matched routes
 * before schema decode refines the values.
 *
 * @example
 * ```ts
 * const params: RouteParams = { id: "123" }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteParams = Record<string, string>;

/** Schema-decoded route params exposed to route components. */
export type DecodedRouteParams = Record<string, unknown>;

/** Cumulative schema-decoded params keyed by each resolved active pattern. */
export type DecodedRouteParamsByPattern = ReadonlyMap<string, DecodedRouteParams>;

/**
 * Current route state
 *
 * @remarks
 * `Route` is the snapshot stored in the router's current-route signal.
 *
 * @example
 * ```ts
 * const route: Route = { path: "/", params: {}, query: new URLSearchParams() }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface Route {
  /** Current path (e.g., "/users/123") */
  readonly path: string;
  /** Extracted route parameters */
  readonly params: RouteParams;
  /** Query string parameters */
  readonly query: URLSearchParams;
  /** Atomic navigation identity and scroll restoration context. */
  readonly navigation: NavigationContext;
}

type NavigateParamsOption<Path extends string> = string extends Path
  ? { readonly params?: Readonly<Record<string, string | number>> }
  : HasKeys<RouteParamsInputFor<Path>> extends true
    ? { readonly params: RouteParamsInputFor<Path> }
    : { readonly params?: never };

/**
 * Navigation options
 *
 * @remarks
 * `NavigateOptions` controls replace behavior plus path-param and query
 * interpolation. Literal dynamic paths require their generated encoded params.
 *
 * @example
 * ```ts
 * const options: NavigateOptions = { replace: true, query: { page: "2" } }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type NavigateOptions<Path extends string = string> = {
  /** Replace current history entry instead of pushing */
  readonly replace?: boolean;
  /** Query parameters to set */
  readonly query?: RouteQueryInputFor<Path>;
} & NavigateParamsOption<Path>;

/** @internal */
export type NavigateArguments<Path extends string> = string extends Path
  ? readonly [options?: NavigateOptions<Path>]
  : HasKeys<RouteParamsInputFor<Path>> extends true
    ? readonly [options: NavigateOptions<Path>]
    : readonly [options?: NavigateOptions<Path>];

/**
 * Options for Router.isActive check.
 *
 * @remarks
 * `IsActiveOptions` lets callers request exact matching or interpolate the
 * generated encoded path params before active-state comparison.
 *
 * @example
 * ```ts
 * const options: IsActiveOptions = { exact: true }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type IsActiveOptions<Path extends string = string> = {
  /** If true, path must match exactly. If false (default), prefix matching is used. */
  readonly exact?: boolean;
} & NavigateParamsOption<Path>;

/** @internal */
export type IsActiveArguments<Path extends string> = string extends Path
  ? readonly [options?: IsActiveOptions<Path>]
  : HasKeys<RouteParamsInputFor<Path>> extends true
    ? readonly [options: IsActiveOptions<Path>]
    : readonly [options?: IsActiveOptions<Path>];

/**
 * Route error info - available to .error() boundary components via RouteError FiberRef
 *
 * @remarks
 * `RouteErrorInfo` is the structured error payload surfaced through
 * `Router.currentError` while an error boundary renders.
 *
 * @example
 * ```ts
 * const info: RouteErrorInfo = { cause, path: "/users", reset: Effect.void }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouteErrorInfo {
  /** The cause of the error - use Cause.squash for display, Cause.match for pattern matching */
  readonly cause: Cause.Cause<unknown>;
  /** The route path that errored */
  readonly path: string;
  /** Reset effect to retry rendering the route - use in onClick handler */
  readonly reset: Effect.Effect<void, never, never>;
}

/**
 * Navigation context set by the router before each route signal update.
 * Read by the outlet to determine scroll behavior after route matching.
 * @since 1.0.0
 * @internal
 */
export interface NavigationContext {
  readonly navigationId: number;
  readonly isPopstate: boolean;
  readonly hash: string;
  readonly scrollKey: string;
}

/**
 * Router service interface
 *
 * @remarks
 * `RouterService` is the runtime contract implemented by `browserLayer` and
 * `testLayer`, then exposed through the `Router` service tag.
 *
 * @example
 * ```ts
 * const router: RouterService = yield* Router.get
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouterService {
  /** Signal containing current route state */
  readonly current: Signal<Route>;

  /**
   * Settle a serialized history transition and publish its snapshot when still current.
   * Completion does not await the Outlet's DOM replacement or scroll application.
   */
  readonly navigate: <Path extends RoutePath>(
    path: Path,
    ...options: NavigateArguments<Path>
  ) => Effect.Effect<void, NavigationError>;

  /** Go back in history */
  readonly back: () => Effect.Effect<void, NavigationError>;

  /** Go forward in history */
  readonly forward: () => Effect.Effect<void, NavigationError>;

  /** Get current route params (type-safe by path pattern) */
  readonly params: <Path extends RoutePath>(
    path: Path,
  ) => Effect.Effect<RouteParamsFor<Path>, RouteParamsPatternMismatch>;

  /** Get query params signal */
  readonly query: Signal<URLSearchParams>;

  /**
   * Derive a reactive Signal\<boolean\> that tracks whether a path is active.
   *
   * Returns a `Signal<boolean>` that can be passed directly to JSX attributes
   * for fine-grained DOM updates without component re-render.
   *
   * Use `Signal.get` on the result if you need the current boolean value
   * (this subscribes the component to route changes).
   *
   * @since 1.0.0
   */
  readonly isActive: <Path extends RoutePath>(
    path: Path,
    ...options: IsActiveArguments<Path>
  ) => Effect.Effect<Signal<boolean>, NavigationError, Scope.Scope>;

  /**
   * Prefetch route modules for a path.
   * Loads all modules (component, layouts) for the matched route into cache.
   * Best-effort: failures are silently ignored.
   * @since 1.0.0
   */
  readonly prefetch: (path: string) => Effect.Effect<void>;

  /**
   * Public seam used by Outlet to coordinate prefetch and scroll effects.
   * Keeps route rendering decoupled from router service internals.
   */
  readonly outletCoordination: OutletCoordination;

  /**
   * Save current scroll position (best-effort, errors ignored).
   * @internal
   */
  readonly _saveScroll: Effect.Effect<void>;
}

/**
 * Outlet prefetch lifecycle state.
 *
 * Idle is the pre-mount state where router.prefetch is a no-op. Active starts
 * after Outlet mounts and registers a resolver built from its route matcher.
 *
 * @public
 * @since 1.0.0
 */
export type OutletPrefetchState = NavigationPrefetchState;

/**
 * Describe the post-swap scroll decision resolved for an Outlet activation.
 *
 * @remarks
 * `strategy`, `hash`, `isPopstate`, and `scrollKey` identify the strategy and
 * activation intent used for the decision. `restored` is present only when
 * `kind` is `"restore"`: `true` means a saved position was applied, while
 * `false` means no position existed for that history entry.
 *
 * Scroll application converts a non-empty `Cause` to `"ignoredError"` only
 * when all of its reasons are typed `Fail` reasons. A `Cause` containing `Die`
 * or `Interrupt`, including a mixed Cause, is preserved and produces no payload.
 *
 * @example
 * ```ts
 * const payload: ScrollApplyPayload = {
 *   kind: "restore",
 *   strategy: "Auto",
 *   hash: "",
 *   isPopstate: true,
 *   scrollKey: "history-entry-4",
 *   restored: true,
 * }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface ScrollApplyPayload {
  /** `none`, `hash`, `restore`, `top`, or recovered typed failure. */
  readonly kind: "none" | "hash" | "restore" | "top" | "ignoredError";
  /** Resolved scroll strategy tag. */
  readonly strategy: ScrollStrategyType["_tag"];
  /** Hash carried by the activation, whether or not it resolved to an element. */
  readonly hash: string;
  /** Whether the activation came from browser history traversal. */
  readonly isPopstate: boolean;
  /** History-entry key used for restoration. */
  readonly scrollKey: string;
  /** Present for `restore`: whether a saved position was found and applied. */
  readonly restored?: boolean;
}

/**
 * Coordinate Outlet prefetch readiness and activation-owned scroll work.
 *
 * @remarks
 * The Router service captures platform dependencies while the Outlet owns the
 * exact DOM-swap acknowledgement and passes the matching navigation intent.
 * Scroll application recovers all-`Fail` Causes as `ignoredError`; `Die`,
 * `Interrupt`, and mixed Causes remain failures.
 *
 * @example
 * ```ts
 * declare const router: RouterService
 * const coordination: OutletCoordination = router.outletCoordination
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface OutletCoordination {
  /** Current prefetch lifecycle state. */
  readonly prefetchState: Effect.Effect<OutletPrefetchState>;

  /**
   * Activate prefetch once the Outlet has mounted and built its matcher.
   */
  readonly activatePrefetch: (
    prefetch: (path: string) => Effect.Effect<void>,
  ) => Effect.Effect<void>;

  /** Wait until an Outlet has installed its prefetch resolver. */
  readonly awaitOutletReady: Effect.Effect<void>;

  /**
   * Apply scroll for an activation after the Outlet acknowledges its exact DOM swap.
   */
  readonly applyScroll: (options: {
    readonly strategy: ScrollStrategyType;
    readonly intent: ScrollIntent;
  }) => Effect.Effect<ScrollApplyPayload, unknown>;
}
