/**
 * Router types for `trygg/router`.
 *
 * @remarks
 * Owner module for the router's shared public types. This module owns the type
 * vocabulary for route params, navigation state, link typing, and the router
 * service interface.
 *
 * ## Type-Safe Routing
 *
 * This module provides type utilities for type-safe navigation:
 *
 * ```tsx
 * // Path autocomplete and param validation
 * <Link to="/users/:id" params={{ id: "123" }}>User</Link>
 *
 * // TypeScript error: missing required param
 * <Link to="/users/:id">User</Link>
 * ```
 * @since 1.0.0
 * @module trygg/router/types
 */
import { Data, Effect, type Cause, type Scope } from "effect";
import { Component } from "../primitives/component.js";
import type { Signal } from "../primitives/signal.js";
import type { Element } from "../primitives/element.js";
import type { ScrollStrategyType } from "./scroll-strategy.js";
import type { NavigationPrefetchState } from "./navigation-outlet-coordination.js";
import {
  compileRoutePathPattern,
  interpolateCompiledRoutePathPattern,
  type InvalidRoutePathPattern,
  type InvalidRoutePathParamValue,
  type MissingRoutePathParam,
  type UnusedRoutePathParam,
} from "./path-pattern.js";

// ==========================================
// Errors
// ==========================================

/**
 * Error representing a failed navigation operation.
 * Wraps underlying platform errors (HistoryError, LocationError, etc.)
 * so consumers can handle navigation failures explicitly.
 *
 * @remarks
 * `NavigationError` is the typed failure surfaced by router navigation helpers
 * when platform history or location work fails.
 *
 * @example
 * ```ts
 * const error = new NavigationError({ operation: "pushState", cause: "boom" })
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export class NavigationError extends Data.TaggedError("NavigationError")<{
  readonly operation: string;
  readonly cause: unknown;
}> {}

/**
 * RouteComponent value was neither a Component.Type nor Effect<Element>.
 * Indicates a bug in route definition or schema validation.
 *
 * @remarks
 * `InvalidRouteComponent` signals that a route component slot received a value
 * outside the supported `RouteComponent | ComponentLoader` surface.
 *
 * @example
 * ```ts
 * const error = new InvalidRouteComponent({ actual: null })
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export class InvalidRouteComponent extends Data.TaggedError("InvalidRouteComponent")<{
  readonly actual: unknown;
}> {}

// ==========================================
// Route Map (augmented by vite plugin)
// ==========================================

/**
 * Route map interface - augmented by vite plugin with actual routes.
 *
 * @remarks
 * `RouteMap` is the declaration-merge target used by the Vite plugin to add
 * concrete route paths and param types to `trygg/router`.
 *
 * When using file-based routing, the vite plugin generates a routes.d.ts
 * that augments this interface with your actual route paths and params.
 *
 * @example
 * ```ts
 * // Generated by vite plugin in routes.d.ts:
 * declare module "trygg/router" {
 *   interface RouteMap {
 *     "/": {}
 *     "/users": {}
 *     "/users/:id": { readonly id: string }
 *   }
 * }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouteMap {
  // Augmented by vite plugin
}

/**
 * Route component type - Component.gen result or Effect<Element>.
 * Can be created with Component.gen or a plain Effect that produces an Element.
 *
 * @remarks
 * `RouteComponent` is the direct component shape the router knows how to render
 * without going through a lazy loader.
 *
 * @example
 * ```ts
 * type Page = RouteComponent
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteComponent =
  | Component.Type<never, unknown, unknown>
  | Effect.Effect<Element, unknown, unknown>;

/**
 * Lazy loader function produced by the vite transform.
 * At build time, `.component(X)` becomes `.component(() => import("./X"))`.
 * The default export must be a RouteComponent.
 *
 * @remarks
 * `ComponentLoader` is the lazy route-component shape used after the Vite
 * transform rewrites eager component references.
 *
 * @example
 * ```ts
 * const loader: ComponentLoader = () => import("./page")
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type ComponentLoader = () => Promise<{ readonly default: unknown }>;

/**
 * Value stored in RouteDefinition component fields.
 * Either a direct RouteComponent (dev/eager) or a ComponentLoader (vite transform/lazy).
 *
 * @remarks
 * `ComponentInput` is the full route-component input surface accepted by route
 * builders and consumed by the outlet.
 *
 * @example
 * ```ts
 * type Input = ComponentInput
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type ComponentInput = RouteComponent | ComponentLoader;

/**
 * Get all route paths from RouteMap.
 * Uses `(string & Record<never, never>)` pattern for autocomplete with string fallback.
 *
 * @remarks
 * `RoutePath` keeps editor autocomplete for known routes while still accepting
 * arbitrary strings before a route map has been generated.
 *
 * @example
 * ```ts
 * const path: RoutePath = "/users/:id"
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RoutePath = keyof RouteMap | (string & Record<never, never>);

// ==========================================
// Type-Safe Routing Utilities
// ==========================================

type CleanParamName<P extends string> = P extends `${infer Name}*`
  ? Name
  : P extends `${infer Name}+`
    ? Name
    : P;

/**
 * Extract route params from a path pattern.
 * Uses template literal types to parse :param segments.
 *
 * @remarks
 * `ExtractRouteParams` is the path-to-param utility used as the fallback when a
 * generated `RouteMap` entry is not available.
 *
 * @example
 * ```ts
 * type P1 = ExtractRouteParams<"/users/:id">
 * // { readonly id: string }
 *
 * type P2 = ExtractRouteParams<"/posts/:postId/comments/:commentId">
 * // { readonly postId: string; readonly commentId: string }
 *
 * type P3 = ExtractRouteParams<"/about">
 * // {}
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type ExtractRouteParams<T extends string> =
  // Handle :param/rest pattern
  T extends `${infer _Start}:${infer Param}/${infer Rest}`
    ? { readonly [K in CleanParamName<Param>]: string } & ExtractRouteParams<`/${Rest}`>
    : // Handle trailing :param pattern
      T extends `${infer _Start}:${infer Param}`
      ? { readonly [K in CleanParamName<Param>]: string }
      : // No params found
        {};

/**
 * Simplify intersection types for better display
 * @internal
 */
type Simplify<T> = { [K in keyof T]: T[K] } & {};

/**
 * Check if a type has any keys
 * @internal
 */
export type HasKeys<T> = keyof T extends never ? false : true;

/**
 * Get route params type for a path.
 * Uses RouteMap if available (from vite plugin), otherwise extracts from path pattern.
 *
 * @remarks
 * `RouteParamsFor` is the main path-to-param helper used by `Link`,
 * `Router.params`, and typed navigation helpers.
 *
 * @example
 * ```ts
 * // With RouteMap (vite plugin):
 * type P1 = RouteParamsFor<"/users/:id">  // RouteMap["/users/:id"]
 *
 * // Without RouteMap (fallback):
 * type P2 = RouteParamsFor<"/posts/:postId">  // { readonly postId: string }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteParamsFor<Path extends string> = Path extends keyof RouteMap
  ? Simplify<RouteMap[Path]>
  : Simplify<ExtractRouteParams<Path>>;

/**
 * Props for type-safe Link component.
 *
 * @remarks
 * `TypeSafeLinkProps` expresses the core conditional typing used by `LinkProps`
 * without the extra forwarded-attribute fields.
 *
 * When the path contains dynamic segments (`:param`), the `params` prop is required.
 * When the path is static, `params` is optional/unnecessary.
 *
 * @example
 * ```tsx
 * // Static path - no params needed
 * <Link to="/">Home</Link>
 *
 * // Dynamic path - params required
 * <Link to="/users/:id" params={{ id: "123" }}>User</Link>
 *
 * // TypeScript enforces correct param names
 * <Link to="/users/:id" params={{ wrong: "x" }}>Error!</Link>
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type TypeSafeLinkProps<Path extends string> =
  HasKeys<RouteParamsFor<Path>> extends true
    ? {
        readonly to: Path;
        readonly params: RouteParamsFor<Path>;
        readonly query?: Record<string, string>;
        readonly replace?: boolean;
        readonly children?: unknown;
        readonly className?: string;
      }
    : {
        readonly to: Path;
        readonly params?: never;
        readonly query?: Record<string, string>;
        readonly replace?: boolean;
        readonly children?: unknown;
        readonly className?: string;
      };

/**
 * Build a URL path by substituting params into a pattern.
 *
 * @remarks
 * `buildPathWithParams` is the typed path interpolator used when a route path
 * and its params should stay aligned at compile time.
 *
 * @example
 * ```ts
 * buildPathWithParams("/users/:id", { id: "123" })
 * // "/users/123"
 *
 * buildPathWithParams("/posts/:postId/comments/:commentId", { postId: "1", commentId: "2" })
 * // "/posts/1/comments/2"
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export const buildPathWithParams = <Path extends string>(
  path: Path,
  params: RouteParamsFor<Path>,
): Effect.Effect<
  string,
  | InvalidRoutePathPattern
  | MissingRoutePathParam
  | UnusedRoutePathParam
  | InvalidRoutePathParamValue
> =>
  Effect.gen(function* () {
    const pattern = yield* compileRoutePathPattern(path);
    return yield* interpolateCompiledRoutePathPattern(pattern, params);
  });

/**
 * Interpolate params into a path pattern using NavigateOptions.params.
 * Handles both string and number values (numbers are converted via String()).
 *
 * @example
 * ```ts
 * interpolateParams("/users/:id", { id: 123 })
 * // "/users/123"
 * ```
 *
 * @internal
 */
export const interpolateParams = (
  path: string,
  params: Record<string, string | number>,
): Effect.Effect<
  string,
  | InvalidRoutePathPattern
  | MissingRoutePathParam
  | UnusedRoutePathParam
  | InvalidRoutePathParamValue
> =>
  Effect.gen(function* () {
    const pattern = yield* compileRoutePathPattern(path);
    return yield* interpolateCompiledRoutePathPattern(pattern, params);
  });

// ==========================================
// Basic Types
// ==========================================

/**
 * Route parameters extracted from path
 *
 * @remarks
 * `RouteParams` is the raw string-valued param record stored on matched routes
 * before schema decode refines the values.
 *
 * @example
 * ```ts
 * const params: RouteParams = { id: "123" }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export type RouteParams = Record<string, string>;

/**
 * Current route state
 *
 * @remarks
 * `Route` is the snapshot stored in the router's current-route signal.
 *
 * @example
 * ```ts
 * const route: Route = { path: "/", params: {}, query: new URLSearchParams() }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface Route {
  /** Current path (e.g., "/users/123") */
  readonly path: string;
  /** Extracted route parameters */
  readonly params: RouteParams;
  /** Query string parameters */
  readonly query: URLSearchParams;
}

/**
 * Navigation options
 *
 * @remarks
 * `NavigateOptions` controls replace behavior plus optional path-param and
 * query interpolation during navigation.
 *
 * @example
 * ```ts
 * const options: NavigateOptions = { replace: true, query: { page: "2" } }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface NavigateOptions {
  /** Replace current history entry instead of pushing */
  readonly replace?: boolean;
  /** Query parameters to set */
  readonly query?: Record<string, string>;
  /** Path params to interpolate into path pattern (e.g., { id: 123 } for "/users/:id") */
  readonly params?: Record<string, string | number>;
}

/**
 * Options for Router.isActive check.
 *
 * @remarks
 * `IsActiveOptions` lets callers request exact matching or interpolate path
 * params before active-state comparison.
 *
 * @example
 * ```ts
 * const options: IsActiveOptions = { exact: true }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface IsActiveOptions {
  /** Path params to interpolate before comparison (e.g., { id: 123 } for "/users/:id") */
  readonly params?: Record<string, string | number>;
  /** If true, path must match exactly. If false (default), prefix matching is used. */
  readonly exact?: boolean;
}

/**
 * Route error info - available to .error() boundary components via RouteError FiberRef
 *
 * @remarks
 * `RouteErrorInfo` is the structured error payload surfaced through
 * `Router.currentError` while an error boundary renders.
 *
 * @example
 * ```ts
 * const info: RouteErrorInfo = { cause, path: "/users", reset: Effect.void }
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouteErrorInfo {
  /** The cause of the error - use Cause.squash for display, Cause.match for pattern matching */
  readonly cause: Cause.Cause<unknown>;
  /** The route path that errored */
  readonly path: string;
  /** Reset effect to retry rendering the route - use in onClick handler */
  readonly reset: Effect.Effect<void, never, never>;
}

/**
 * Navigation context set by the router before each route signal update.
 * Read by the outlet to determine scroll behavior after route matching.
 * @since 1.0.0
 * @internal
 */
export interface NavigationContext {
  readonly isPopstate: boolean;
  readonly hash: string;
  readonly scrollKey: string;
}

/**
 * Router service interface
 *
 * @remarks
 * `RouterService` is the runtime contract implemented by `browserLayer` and
 * `testLayer`, then exposed through the `Router` service tag.
 *
 * @example
 * ```ts
 * const router: RouterService = yield* Router.get
 * ```
 *
 * @category Route Types
 * @public
 * @since 1.0.0
 */
export interface RouterService {
  /** Signal containing current route state */
  readonly current: Signal<Route>;

  /** Navigate to a path. Fails with NavigationError if history/location operations fail. */
  readonly navigate: (
    path: string,
    options?: NavigateOptions,
  ) => Effect.Effect<void, NavigationError>;

  /** Go back in history */
  readonly back: () => Effect.Effect<void>;

  /** Go forward in history */
  readonly forward: () => Effect.Effect<void>;

  /** Get current route params (type-safe by path pattern) */
  readonly params: <Path extends RoutePath>(path: Path) => Effect.Effect<RouteParamsFor<Path>>;

  /** Get query params signal */
  readonly query: Signal<URLSearchParams>;

  /**
   * Derive a reactive Signal\<boolean\> that tracks whether a path is active.
   *
   * Returns a `Signal<boolean>` that can be passed directly to JSX attributes
   * for fine-grained DOM updates without component re-render.
   *
   * Use `Signal.get` on the result if you need the current boolean value
   * (this subscribes the component to route changes).
   *
   * @since 1.0.0
   */
  readonly isActive: (
    path: string,
    options?: IsActiveOptions,
  ) => Effect.Effect<Signal<boolean>, never, Scope.Scope>;

  /**
   * Prefetch route modules for a path.
   * Loads all modules (component, layouts) for the matched route into cache.
   * Best-effort: failures are silently ignored.
   * @since 1.0.0
   */
  readonly prefetch: (path: string) => Effect.Effect<void>;

  /**
   * Public seam used by Outlet to coordinate prefetch and scroll effects.
   * Keeps route rendering decoupled from router service internals.
   */
  readonly outletCoordination: OutletCoordination;

  /**
   * Save current scroll position (best-effort, errors ignored).
   * @internal
   */
  readonly _saveScroll: Effect.Effect<void>;
}

/**
 * Outlet prefetch lifecycle state.
 *
 * Idle is the pre-mount state where router.prefetch is a no-op. Active starts
 * after Outlet mounts and registers a resolver built from its route matcher.
 *
 * @public
 * @since 1.0.0
 */
export type OutletPrefetchState = NavigationPrefetchState;

/**
 * Verifier-facing scroll decision applied after route activation commits DOM.
 *
 * @public
 * @since 1.0.0
 */
export interface ScrollApplyPayload {
  readonly kind: "none" | "hash" | "restore" | "top" | "ignoredError";
  readonly strategy: ScrollStrategyType["_tag"];
  readonly hash: string;
  readonly isPopstate: boolean;
  readonly scrollKey: string;
  readonly restored?: boolean;
}

/**
 * Public coordination seam from Router service to Outlet.
 *
 * @public
 * @since 1.0.0
 */
export interface OutletCoordination {
  /** Current prefetch lifecycle state. */
  readonly prefetchState: Effect.Effect<OutletPrefetchState>;

  /**
   * Activate prefetch once the Outlet has mounted and built its matcher.
   */
  readonly activatePrefetch: (
    prefetch: (path: string) => Effect.Effect<void>,
  ) => Effect.Effect<void>;

  /**
   * Apply scroll behavior using router-captured platform services.
   */
  readonly applyScroll: (options: {
    readonly strategy: ScrollStrategyType;
  }) => Effect.Effect<ScrollApplyPayload>;
}
