// Auto-generated by trygg
import type * as Context from "effect/Context";
import type { Layer } from "effect/Layer";
import type { HttpApiClient } from "effect/unstable/httpapi";
import type { Api } from "./app/api";

type ApiClientService = HttpApiClient.ForApi<typeof Api>;

declare module "trygg/api" {
  export interface ApiClient {}
  export const ApiClient: Context.ServiceClass<ApiClient, "ApiClient", ApiClientService>;
  export const ApiClientLive: Layer.Layer<ApiClient>;
  export { Api };
}
