// Auto-generated by effect-ui vite plugin
// DO NOT EDIT - This file is regenerated when routes change

// Augment the RouteMap interface with actual routes for type-safe navigation
declare module "effect-ui/router" {
  interface RouteMap {
    readonly "/counter": {}
    readonly "/dashboard": {}
    readonly "/error-boundary": {}
    readonly "/error-demo": {}
    readonly "/form": {}
    readonly "/": {}
    readonly "/login": {}
    readonly "/protected": {}
    readonly "/settings": {}
    readonly "/settings/profile": {}
    readonly "/settings/security": {}
    readonly "/theme": {}
    readonly "/todo": {}
    readonly "/users/:id": { readonly id: string }
    readonly "/users": {}
  }
}

export {}
